### ISSUE TITLE
searching doesn't work anymore

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/POL-POM-5#1085]
How to reproduce:
1. Go to "Applications"
2. Search for "tomb" (like in Tomb Raider)

you get:
```
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: fromIndex = -1
	at java.util.SubList.<init>(AbstractList.java:620)
	at java.util.RandomAccessSubList.<init>(AbstractList.java:775)
	at java.util.AbstractList.subList(AbstractList.java:484)
	at javafx.collections.ModifiableObservableListBase.subList(ModifiableObservableListBase.java:189)
	at com.sun.javafx.binding.ContentBinding$ListContentBinding.onChanged(ContentBinding.java:114)
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:524)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.transformation.SortedList.sourceChanged(SortedList.java:108)
	at javafx.collections.transformation.TransformationList.lambda$getListener$1(TransformationList.java:106)
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:524)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at org.phoenicis.javafx.views.common.lists.PhoenicisFilteredList.trigger(PhoenicisFilteredList.java:250)
	at com.sun.javafx.application.PlatformImpl.lambda$null$117(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$118(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by plata** [comment]
The search in "Library" seems to be ok.

**Comment by madoar** [comment]
I can't reproduce this. I've tried all six keywords, and the search always worked without throwing an exception.

**Comment by plata** [comment]
It's somehow related to my local repositories.

**Comment by plata** [comment]
Try this:
1. create a repositories.json with a local repository
    ```Json
    [{"repositoryLocation":"/home/plata/.Phoenicis/repository","type":"local"}]
    ```
2. search for "tomb" → should work
3. copy the `repository` folder to `repository2` and change your repositories.json to
    ```Json
    [{"repositoryLocation":"/home/plata/.Phoenicis/repository","type":"local"}, {"repositoryLocation":"/home/plata/.Phoenicis/repository2","type":"local"}]
    ```
4. search for "tomb" → should fail

**Comment by madoar** [comment]
So basically we have a problem with the merging process of two repositories, and its effects on the application/category list?
I'll test this tomorrow

**Comment by madoar** [comment]
Ok... The problem is located inside the `SortedList` class. This class takes 2 subchange events and produces 4 subchange events, from which one takes the index range [-1, -1].
When you swap the order of the lists:
```java
        // initialising the application lists
        this.applications = new ExpandedList<ApplicationDTO, CategoryDTO>(this.installableCategories,
                CategoryDTO::getApplications);
        this.sortedApplications = this.applications.sorted(Comparator.comparing(ApplicationDTO::getName));
        this.filteredApplications = new PhoenicisFilteredList<ApplicationDTO>(this.sortedApplications, filter::filter);
        filter.addOnFilterChanged(filteredApplications::trigger);
        
        this.sidebar = new ApplicationSidebar(availableApps, filter, javaFxSettingsManager);

        // create the bindings between the visual components and the observable lists
        this.sidebar.bindCategories(this.sortedCategories);
        this.availableApps.bind(this.filteredApplications);
```
you don't get the error...

Now the big question: Is this error located in our list implementation or in the `SortedList` class?

**Comment by plata** [comment]
I just don't understand why this happens only with more than 1 repository. I debugged the repository yesterday and it seemed like the merge was ok. So how can the `SortedList` even know that there have been multiple repositories?

**Comment by madoar** [comment]
I don't know.
One possibility is, that the change events that are passed to the `SortedList` are somehow in an order, that can't be processed by the `SortedList`, or are processed wrong.
For example, if our filtered list first removes items and afterwards adds items, while the sorted list processes these changes in the other order, i.e. first add items and remove items afterwards, it may lead to some problems.

Let's assume the list `1, 2, 3, 4, 5`. We first remove the second element and afterwards add a new third element we get `1, 3, x, 4, 5`. Now the events are forwarded to the next list, which processes these changes in the other order, which results in `1, x, 3, 4, 5`.

**Comment by plata** [comment]
Still there must be a difference between 1 repository and 1 merge repository with exactly the same content.
