### ISSUE TITLE
Nothing happen when clicking on a container

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/POL-POM-5#1122]
Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at org.phoenicis.javafx.views.mainwindow.containers.ContainerPanelFactory.createContainerPanel(ContainerPanelFactory.java:52)
	at org.phoenicis.javafx.controller.containers.ContainersController.lambda$new$8(ContainersController.java:86)
	at org.phoenicis.javafx.views.mainwindow.containers.ContainersView.showContainerDetails(ContainersView.java:130)
	at org.phoenicis.javafx.views.mainwindow.containers.ContainersView.lambda$new$0(ContainersView.java:77)
	at org.phoenicis.javafx.views.common.widgets.lists.CombinedListWidget.lambda$new$0(CombinedListWidget.java:67)
	at org.phoenicis.javafx.views.common.widgets.lists.icons.IconsListWidget.lambda$null$0(IconsListWidget.java:84)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:416)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.phoenicis.javafx.views.mainwindow.containers.ContainerPanelFactory.createContainerPanel(ContainerPanelFactory.java:48)
	... 41 more
Caused by: java.lang.NullPointerException
	at org.phoenicis.javafx.views.mainwindow.containers.WinePrefixContainerWineToolsTab.populate(WinePrefixContainerWineToolsTab.java:61)
	at org.phoenicis.javafx.views.mainwindow.containers.WinePrefixContainerWineToolsTab.<init>(WinePrefixContainerWineToolsTab.java:47)
	at org.phoenicis.javafx.views.mainwindow.containers.WinePrefixContainerPanel.<init>(WinePrefixContainerPanel.java:47)
	... 46 more
`

**Comment by plata** [comment]
Just checked on current master with up-to-date scripts repository. Couldn't reproduce your issue.

**Comment by ImperatorS79** [comment]
The issue only happen with my French translation...

**Comment by plata** [comment]
Of the scripts or the software?

**Comment by ImperatorS79** [comment]
Of the software. If I build POL with only "Library" ans "Apps" translated, no problems. But with full fr.po, container tab isn't working.

**Comment by plata** [comment]
Can you check if the tool names are translated?

**Comment by ImperatorS79** [comment]
I have 144/144 strings translated. What "tools" do you speak of ?

**Comment by plata** [comment]
Not quite sure yet. I can only think that some ID is translated and then it cannot find the tool anymore. I will have to try myself.

**Comment by plata** [comment]
Can you try what happens if you change `WinePrefixContainerWineToolsTab#populate` to:
```Java
private void populate(ApplicationDTO engineTools) {
        final VBox toolsPane = new VBox();
        final Text title = new TextWithStyle(tr("Wine tools"), TITLE_CSS_CLASS);

        if (engineTools == null) {
                return;
        }
```

**Comment by ImperatorS79** [comment]
It works now

**Comment by ImperatorS79** [comment]
I have a similar problem with the engines tab : nothing with translations.

**Comment by plata** [comment]
In case someone wants to debug this in a non-French environment: call Phoenicis with JVM parameter `-Duser.language=fr`.

**Comment by plata** [comment]
Ok. The problem is that "Engines" is translated. Therefore, `fetchAvailableEngineTools` cannot find them.
