### ISSUE TITLE
NPE on edit applications settings

### ISSUE THREAD

**Issue by Amosar** [PhoenicisOrg/POL-POM-5#1132]
Hello, I have found an NPE when I want to save modification on an application
I juste want to remove the Wine Debug flag
https://pastebin.com/pVU6P4cb
![playonlinuxaplicationbug](https://user-images.githubusercontent.com/14032531/30514475-f3c6d0a2-9b0c-11e7-95cd-c239b7dd7945.png)

System informations:
linux mint 18.2 with kde
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by plata** [comment]
That's strange. I remove the debug flag all the time.

**Comment by plata** [comment]
Is your software up-to-date? I just checked the line where the exception occurs. I don't see how it could happen there.

**Comment by ImperatorS79** [comment]
I got this error, on an english version : 

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at org.phoenicis.library.ShortcutManager.updateShortcut(ShortcutManager.java:166)                                                                                          
        at org.phoenicis.javafx.controller.library.LibraryController.lambda$new$6(LibraryController.java:89)                                                                       
        at org.phoenicis.javafx.views.mainwindow.library.EditShortcutPanel.lambda$setShortcutDTO$2(EditShortcutPanel.java:169)                                                     
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)                                                                         
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)                                                                            
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)                                                                            
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)                                                                   
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)                                                                                   
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)                                                                              
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)                                                                                   
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)                                                                              
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)                                                                                   
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)                                                                              
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)                                                                                   
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)                                                                              
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)                                                                                                         
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)                                                                                                             
        at javafx.event.Event.fireEvent(Event.java:198)                                                                                                                            
        at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)                                                                                                          
        at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)                                                                                                          
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)                                                                                                                
        at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)                                                                                                            
        at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)                                                                                                              
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)                                                                                                        
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:416)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
        at com.sun.glass.ui.View.notifyMouse(View.java:937)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by plata** [comment]
Ok sorry. I look at the wrong line before. No idea why it didn't happen before or doesn't happen to me, BUT: I bet the icon is `null`.

**Comment by ImperatorS79** [comment]
@plata I'm still unable to edit a shortcut, despite using current master

**Comment by plata** [comment]
Same error message?

**Comment by Amosar** [comment]
Yes I have already this error with this same message.
And I have test with clean install with Steam Script for example
If I right click on the element, select edit and save directly I have this error

**Comment by plata** [comment]
But even in the same code line? I mean the code changed there so how could it possibly be the exact same error?

**Comment by Amosar** [comment]
No the line have changed sorry :/
https://pastebin.com/jmCDsuHA

**Comment by plata** [comment]
Do you know how to debug?

**Comment by Amosar** [comment]
I can try, I just need to setup my IDE
I come back to you if I find more info

**Comment by ImperatorS79** [comment]
I get 
```
[ERROR] org.phoenicis.library.ShortcutManager (l.170) - shortcutIcon.getPath() is null
[ERROR] org.phoenicis.library.ShortcutManager (l.171) - jar:file:/home/fevrier/POL5/POL-POM-5/phoenicis-dist/target/phoenicis-dist/lib/phoenicis-library-5.0-SNAPSHOT.jar!/org/phoenicis/library/phoenicis.png
```

**Comment by plata** [comment]
This explains why I don't have the error. I run from my IDE, so I don't have this jar path.

I guess the easiest solution is to check `shortcutDTO.getInfo().getName()` for `null` as well.

**Comment by Amosar** [comment]
Yes I have test to run with my IDE (Intelij) and I don't have this error
You can reproduce the bug if you have installed PlayOnLinux.
You juste need to install new application and try to edit this application.

If you have modify the application with the IDE you can edit application without error

**Comment by Amosar** [comment]
The error is not with the check of null icon it's with the construction of the URI, I have send the log in pull request and I try to correct this too :)
