### ISSUE TITLE
FileNotFoundException on installing new program

### ISSUE THREAD

**Issue by Earl0fPudding** [PhoenicisOrg/POL-POM-5#1144]
Hi,
I am running POL-5 (Git Revision [9e8725c20a8f141808d275a1c2b71127d6ba651d](https://github.com/PhoenicisOrg/POL-POM-5/commit/9e8725c20a8f141808d275a1c2b71127d6ba651d)).
When I try to install a program there is an java.io.FileNotFoundException and the loading bar doesn't load anymore.
It seems POL is looking for a config file for the programs, but I have never installed the program before.

I tried this several times.
While installing Assassin's Creed:
```
[DEBUG] org.phoenicis.tools.config.CompatibleConfigFileFormat (l.88) - Error while reading the file. Will assume that the config file is EMPTY
java.io.FileNotFoundException: /home/weide/.Phoenicis/containers/wineprefix/Assassins Creed/phoenicis.cfg (Datei oder Verzeichnis nicht gefunden)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:753)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2673)
	at org.phoenicis.tools.config.CompatibleConfigFileFormat.getMap(CompatibleConfigFileFormat.java:77)
	at org.phoenicis.tools.config.CompatibleConfigFileFormat.writeValue(CompatibleConfigFileFormat.java:53)
	at jdk.nashorn.internal.scripts.Script$Recompilation$66$2659A$\^eval\_.prefix([Engines, Wine, Engine, Object]:131)
	at jdk.nashorn.internal.scripts.Script$Recompilation$45$2177$\^eval\_.go([Engines, Wine, QuickScript, SteamScript]:104)
	at jdk.nashorn.internal.scripts.Script$27$\^eval\_.:program(<eval>:3)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

While installing The Crew:
```
[DEBUG] org.phoenicis.tools.config.CompatibleConfigFileFormat (l.88) - Error while reading the file. Will assume that the config file is EMPTY
java.io.FileNotFoundException: /home/weide/.Phoenicis/containers/wineprefix/The Crew/phoenicis.cfg (Datei oder Verzeichnis nicht gefunden)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:753)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2673)
	at org.phoenicis.tools.config.CompatibleConfigFileFormat.getMap(CompatibleConfigFileFormat.java:77)
	at org.phoenicis.tools.config.CompatibleConfigFileFormat.writeValue(CompatibleConfigFileFormat.java:53)
	at jdk.nashorn.internal.scripts.Script$Recompilation$160$2659A$\^eval\_.prefix([Engines, Wine, Engine, Object]:131)
	at jdk.nashorn.internal.scripts.Script$Recompilation$139$2177$\^eval\_.go([Engines, Wine, QuickScript, SteamScript]:104)
	at jdk.nashorn.internal.scripts.Script$120$\^eval\_.:program(<eval>:3)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I hope you can help me with this.

**Comment by ImperatorS79** [comment]
I think it is "normal" and it should not bother you to install your app.

**Comment by plata** [comment]
The problem is that we use the same method when loading a container for existing containers and when the container is created. Therefore, you get this error message when you create the container. It should not influence the execution.
However, it's a bug in the sense that this error message should not be printed out.
