### ISSUE TITLE
Program does nothing when clicking on a container in the containers tab

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/POL-POM-5#1200]
I just re-downloaded and builded mysef the program and got this :
```
Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: java.lang.NoSuchMethodException: org.phoenicis.javafx.views.mainwindow.containers.WinePrefixContainerPanel.<init>(org.phoenicis.containers.dto.WinePrefixContainerDTO, java.util.List, org.phoenicis.engines.EngineToolsManager, java.util.Optional, org.phoenicis.containers.wine.WinePrefixContainerController)
        at org.phoenicis.javafx.views.mainwindow.containers.ContainerPanelFactory.createContainerPanel(ContainerPanelFactory.java:53)
        at org.phoenicis.javafx.controller.containers.ContainersController.lambda$new$8(ContainersController.java:80)
        at org.phoenicis.javafx.views.mainwindow.containers.ContainersView.showContainerDetails(ContainersView.java:130)
        at org.phoenicis.javafx.views.mainwindow.containers.ContainersView.lambda$new$0(ContainersView.java:77)
        at org.phoenicis.javafx.views.common.widgets.lists.CombinedListWidget.lambda$new$0(CombinedListWidget.java:67)
        at org.phoenicis.javafx.views.common.widgets.lists.icons.IconsListWidget.lambda$null$0(IconsListWidget.java:84)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
        at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
        at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
        at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:417)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
        at com.sun.glass.ui.View.notifyMouse(View.java:937)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodException: org.phoenicis.javafx.views.mainwindow.containers.WinePrefixContainerPanel.<init>(org.phoenicis.containers.dto.WinePrefixContainerDTO, java.util.List, org.phoenicis.engines.EngineToolsManager, java.util.Optional, org.phoenicis.containers.wine.WinePrefixContainerController)
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.getConstructor(Class.java:1825)
        at org.phoenicis.javafx.views.mainwindow.containers.ContainerPanelFactory.createContainerPanel(ContainerPanelFactory.java:47)
        ... 41 more
```
Also have some 
`[DEBUG] org.phoenicis.library.LibraryManager (l.157) - JSON file not found
`

**Comment by madoar** [comment]
@plata this is strange, why are our tests not failing?

**Comment by plata** [comment]
We have no test for this afaik.
